runtime: nodejs18

instance_class: F2

env_variables:
  NODE_ENV: 'production'

handlers:
  - url: /_next/static
    static_dir: .next/static
  - url: /static
    static_dir: static
  - url: /.*
    script: auto
